---
- name: Install Synology Backup for Business Agent
  hosts: hosts
  become: true
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present

    - name: Create directory for unpacked files
      ansible.builtin.file:
        path: /root/unpacked
        state: directory
        mode: '0755'

    - name: Unpack the ZIP file
      ansible.builtin.unarchive:
        src: ../assets/synology_backup_agent.zip
        dest: /root/unpacked

    - name: Install
      ansible.builtin.command:
        cmd: /root/unpacked/install.run
        creates: /usr/bin/abb-cli

    - name: Run abb-cli command
      ansible.builtin.command:
        cmd: abb-cli --address '{{ lookup('env', 'NAS_IP') }}' --username '{{ lookup('env', 'NAS_USER') }}' --password '{{ lookup('env', 'NAS_PASSWORD') }}' --connect --quiet && touch /root/backup-agent.flag
        creates: /root/backup-agent.flag
