---
- name: Configure UFW Firewall
  hosts: hosts
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Allow ports through UFW
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
      with_items: [22, 80, 443]

    - name: Set default incoming policy to deny
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Set default outgoing policy to allow
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Enable UFW
      community.general.ufw:
        state: enabled
