---
- name: Manage Docker containers
  hosts: hosts
  become: true
  handlers:
    - name: Restart docker containers
      ansible.builtin.shell: CLOUDFLARE_DNS_API_TOKEN="{{ lookup('env', 'CLOUDFLARE_DNS_API_TOKEN') }}" docker compose -f /root/compose.yml up -d
  tasks:
    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Create directory for docker data
      ansible.builtin.file:
        path: /DATA
        state: directory
        mode: '0755'

    - name: Copy traefik.yml to the remote host
      ansible.builtin.copy:
        src: ../assets/traefik.yml
        dest: /DATA/traefik/traefik.yml
        mode: '0755'
      notify: Restart docker containers

    - name: Copy compose.yml to the remote host
      ansible.builtin.copy:
        src: ../assets/compose.yml
        dest: /root/compose.yml
        mode: '0755'
      notify: Restart docker containers
